[reset_default_setupvars]
name = "Reset the config file and restore a default one."
command = "/bin/bash scripts/actions/reset_default_config \"setupVars.conf\""
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Reset the config file setupVars.conf."

[reset_default_ftl]
name = "Reset the config file and restore a default one."
command = "/bin/bash scripts/actions/reset_default_config \"pihole-FTL.conf\""
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Reset the config file pihole-FTL.conf."
