packaging_format = 2

id = "pihole"
name = "Pi-hole"
description.en = "Network-wide ad blocking via your own DNS server"
description.fr = "Filtrage publicitaire via votre propre serveur DNS"

version = "5.15.5~ynh1"

maintainers = []

[upstream]
license = "EUPL-1.2"
website = "https://pi-hole.net/"
admindoc = "https://docs.pi-hole.net"
code = "https://github.com/pi-hole/pi-hole"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 11.0.9"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = false
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/pihole"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.query_logging]
    ask.en = "Do you want to log DNS queries?"
    ask.fr = "Voulez-vous enregistrer les requêtes DNS ?"
    help.en = "Keeping this option deactivate will render graphs on the admin page useless. But will respect the privacy of the other users."
    help.fr = "Garder cette option désactivée rendra les graphiques sur la page d'administration inutiles. Mais respectera la vie privée des autres utilisateurs."
    type = "boolean"
    default = false

    [install.enable_dhcp]
    ask.en = "Do you want to set Pi-Hole as your DHCP server?"
    ask.fr = "Voulez-vous utiliser Pi-Hole an tant que serveur DHCP ?"
    help.en = "If you want to do that, <a href=https://github.com/YunoHost-Apps/pihole_ynh/blob/master/dhcp.md target=_blank>you really have to read this before</a>!"
    help.fr = "Si vous voulez faire ça, <a href=https://github.com/YunoHost-Apps/pihole_ynh/blob/master/dhcp.md target=_blank>vous devez vraiment lire cela avant</a> !"
    type = "boolean"
    default = false

[resources]
    [resources.sources]
        [resources.sources.pi-hole_AdminLTE]
        url = "https://github.com/pi-hole/AdminLTE/archive/v5.18.4.tar.gz"
        sha256 = "25095ead3132aecad193537d8856e291b923cb70db0da1b7d00600caca9b8a97"

        [resources.sources.pi-hole_Core]
        url = "https://github.com/pi-hole/pi-hole/archive/v5.15.5.tar.gz"
        sha256 = "fa723c7573b0441b5f28300313eb99508853df1752720208f6cf6008da63abc2"

        [resources.sources.pi-hole_FTL]
        url = "https://github.com/pi-hole/FTL/archive/v5.21.tar.gz"
        sha256 = "66bbec5a4cb8aa64035ccb275b0c849a062b319dfc64b8c26a32529972b1f998"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
