packaging_format = 2

id = "pihole"
name = "Pi-hole"
description.en = "Network-wide ad blocking via your own DNS server"
description.fr = "Filtrage publicitaire via votre propre serveur DNS"

version = "5.15.5~ynh1"

maintainers = []

[upstream]
license = "EUPL-1.2"
website = "https://pi-hole.net/"
admindoc = "https://docs.pi-hole.net"
code = "https://github.com/pi-hole/pi-hole"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"
[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pihole"

    [install.admin]
    type = "user"

    [install.query_logging]
    ask.en = "Do you want to log DNS queries?"
    ask.fr = "Voulez-vous enregistrer les requêtes DNS ?"
    help.en = "Keeping this option deactivate will render graphs on the admin page useless. But will respect the privacy of the other users."
    help.fr = "Garder cette option désactivée rendra les graphiques sur la page d'administration inutiles. Mais respectera la vie privée des autres utilisateurs."
    type = "boolean"
    default = false

    [install.enable_dhcp]
    ask.en = "Do you want to set Pi-Hole as your DHCP server?"
    ask.fr = "Voulez-vous utiliser Pi-Hole an tant que serveur DHCP ?"
    help.en = "If you want to do that, <a href=https://github.com/YunoHost-Apps/pihole_ynh/blob/master/dhcp.md target=_blank>you really have to read this before</a>!"
    help.fr = "Si vous voulez faire ça, <a href=https://github.com/YunoHost-Apps/pihole_ynh/blob/master/dhcp.md target=_blank>vous devez vraiment lire cela avant</a> !"
    type = "boolean"
    default = false

[resources]
    [resources.sources]
        [resources.sources.pi-hole_AdminLTE]
        url = "https://github.com/pi-hole/AdminLTE/archive/v5.18.4.tar.gz"
        sha256 = "25095ead3132aecad193537d8856e291b923cb70db0da1b7d00600caca9b8a97"

        [resources.sources.pi-hole_Core]
        url = "https://github.com/pi-hole/pi-hole/archive/v5.15.5.tar.gz"
        sha256 = "fa723c7573b0441b5f28300313eb99508853df1752720208f6cf6008da63abc2"

        [resources.sources.pi-hole_FTL]
        url = "https://github.com/pi-hole/FTL/archive/v5.21.tar.gz"
        sha256 = "66bbec5a4cb8aa64035ccb275b0c849a062b319dfc64b8c26a32529972b1f998"

    [resources.ports]
    main.default = 4711

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"

    [resources.apt]
    packages = "php8.0-common php8.0-cgi php8.0-sqlite3 php8.0-xml php8.0-intl cmake build-essential libgmp-dev libidn11-dev nettle-dev libreadline-dev sqlite3 cron curl iputils-ping psmisc unzip idn2 libcap2-bin dns-root-data libcap2 netcat-openbsd procps jq"
