#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pihole"
name = "Pi-hole"
description.en = "Network-wide ad blocking via your own DNS server"
description.fr = "Filtrage publicitaire via votre propre serveur DNS"

version = "6.0.5~ynh1"

maintainers = []

[upstream]
license = "EUPL-1.2"
website = "https://pi-hole.net/"
admindoc = "https://docs.pi-hole.net"
code = "https://github.com/pi-hole/pi-hole"
fund = "https://pi-hole.net/donate/#donate"

[integration]
yunohost = ">= 11.2.4"
architectures = "all"
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "200M"
ram.build = "600M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    #[install.path]
    #type = "path"
    #default = "/pihole"

    [install.query_logging]
    ask.en = "Do you want to log DNS queries?"
    ask.fr = "Voulez-vous enregistrer les requêtes DNS ?"
    help.en = "Keeping this option deactivate will render graphs on the admin page useless. But will respect the privacy of the other users."
    help.fr = "Garder cette option désactivée rendra les graphiques sur la page d'administration inutiles. Mais respectera la vie privée des autres utilisateurs."
    type = "boolean"
    default = false

    [install.enable_dhcp]
    ask.en = "Do you want to set Pi-Hole as your DHCP server?"
    ask.fr = "Voulez-vous utiliser Pi-Hole an tant que serveur DHCP ?"
    help.en = "If you want to do that, <a href=https://github.com/YunoHost-Apps/pihole_ynh/blob/master/dhcp.md target=_blank>you really have to read this before</a>!"
    help.fr = "Si vous voulez faire ça, <a href=https://github.com/YunoHost-Apps/pihole_ynh/blob/master/dhcp.md target=_blank>vous devez vraiment lire cela avant</a> !"
    type = "boolean"
    default = false

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/pi-hole/pi-hole/archive/refs/tags/v6.0.5.tar.gz"
    sha256 = "912f5cf1641dc506eaf30813d2dd35722ea1fe7a1f91d5334b19c553c9fd43c6"
    autoupdate.upstream = "https://github.com/pi-hole/pi-hole"
    autoupdate.strategy = "latest_github_release"

    [resources.sources.pi-hole_web]
    url = "https://github.com/pi-hole/web/archive/refs/tags/v6.0.2.tar.gz"
    sha256 = "705772ea91e73c441efaa18b4512af58647dba5309b2784cb674116b972af4d6"
    autoupdate.upstream = "https://github.com/pi-hole/web"
    autoupdate.strategy = "latest_github_release"

    [resources.sources.pi-hole_ftl]
    amd64.url = "https://github.com/pi-hole/FTL/releases/download/v6.0.4/pihole-FTL-amd64"
    amd64.sha256 = "4e765fef842a2609bdb7ec7aaf3bdf726c61af633b9bcbd9d127f00e3fd0eba6"
    i386.url = "https://github.com/pi-hole/FTL/releases/download/v6.0.4/pihole-FTL-386"
    i386.sha256 = "9d7f3514ae193ae502539eecb85fa640bf35ee2d087bf2d01ee073af39df2eab"
    armhf.url = "https://github.com/pi-hole/FTL/releases/download/v6.0.4/pihole-FTL-armv6"
    armhf.sha256 = "eb9901ecb554a6f9ecc00e11a3243641351da3ada5e8d431eb519416ab09c68b"
    arm64.url = "https://github.com/pi-hole/FTL/releases/download/v6.0.4/pihole-FTL-arm64"
    arm64.sha256 = "117c1f9a8594227b60c05c4c1be42d6ed64969c27201e7f27685dc2272b1521b"

    autoupdate.upstream = "https://github.com/pi-hole/FTL"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "pihole-FTL-amd64"
    autoupdate.asset.i386 = ".ihole-FTL-386"
    autoupdate.asset.armhf = "pihole-FTL-armv6"
    autoupdate.asset.arm64 = "pihole-FTL-arm64"

    rename = "pihole-FTL"
    extract = "false"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"

    [resources.ports]
    main.default = 4711
    web.default = 8080

    [resources.apt]
    packages = [
        "bash-completion",
        "binutils",
        "ca-certificates",
        "cron",
        "curl",
        "dialog",
        "dns-root-data",
        "dnsutils",
        "git",
        "grep",
        "iproute2",
        "iputils-ping",
        "jq",
        "libcap2",
        "libcap2-bin",
        "lshw",
        "netcat-openbsd",
        "procps",
        "psmisc",
        "sudo",
        "unzip",
    ]
