#!/bin/bash

if [ "$YNH_APP_ARG_PIHOLE_VERSION" == "Last 3.X" ]
then
    pihole_core_version=3.3.1
    dashboard_version=3.3
    FTL_version=3.0
else
    pihole_core_version=5.6
    dashboard_version=5.8
    FTL_version=5.11
fi
