#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

if [ ! -e _common.sh ]; then
	# Get the _common.sh file if it's not in the current directory
	cp ../settings/scripts/_common.sh ./_common.sh
	chmod a+rx _common.sh
fi
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP OF THE MAIN DIRECTORIES OF THE APP
#=================================================

CHECK_SIZE "$final_path"
ynh_backup "$final_path"

CHECK_SIZE "/etc/.pihole"
ynh_backup "/etc/.pihole"

CHECK_SIZE "/etc/pihole"
ynh_backup "/etc/pihole"

CHECK_SIZE "/opt/pihole"
ynh_backup "/opt/pihole"

#=================================================
# BACKUP OF THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# BACKUP OF THE PHP-FPM CONFIGURATION
#=================================================

ynh_backup "/etc/php5/fpm/pool.d/$app.conf"
ynh_backup "/etc/php5/fpm/conf.d/20-$app.ini"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP OF THE CRON FILE
#=================================================

ynh_backup "/etc/cron.d/pihole"

#=================================================
# BACKUP OF SPECIFIC FILES
#=================================================

ynh_backup "/usr/local/bin/pihole"
ynh_backup "/etc/bash_completion.d/pihole"

ynh_backup "/etc/sudoers.d/pihole"

ynh_backup "/etc/init.d/pihole-FTL"
ynh_backup "/usr/bin/pihole-FTL"

ynh_backup "/etc/dnsmasq.d/01-pihole.conf"
if test -e "/etc/dnsmasq.d/02-pihole-dhcp.conf"; then
	ynh_backup "/etc/dnsmasq.d/02-pihole-dhcp.conf"
fi
if test -e "/etc/dnsmasq.d/03-pihole-wildcard.conf"; then
	ynh_backup "/etc/dnsmasq.d/03-pihole-wildcard.conf"
fi
if test -e "/etc/dnsmasq.d/04-pihole-static-dhcp.conf"; then
	ynh_backup "/etc/dnsmasq.d/04-pihole-static-dhcp.conf"
fi

ynh_backup "/usr/share/yunohost/hooks/conf_regen/50-dnsmasq_$app"
