#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Load common variables for all scripts.
source _variables

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
query_logging=$YNH_APP_ARG_QUERY_LOGGING
enable_dhcp=$YNH_APP_ARG_ENABLE_DHCP
pihole_version="$YNH_APP_ARG_PIHOLE_VERSION"

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
#=================================================
ynh_script_progression --message="Validating installation parameters..." --weight=2

final_path=/var/www/$app
test ! -e "$final_path" || ynh_die --message="This path already contains a folder"

# Register (book) web path
ynh_webpath_register --app=$app --domain=$domain --path_url=$path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..." --weight=3

ynh_app_setting_set --app=$app --key=domain --value=$domain
ynh_app_setting_set --app=$app --key=path --value=$path_url
ynh_app_setting_set --app=$app --key=admin --value=$admin
ynh_app_setting_set --app=$app --key=query_logging --value=$query_logging
ynh_app_setting_set --app=$app --key=enable_dhcp --value=$enable_dhcp
ynh_app_setting_set --app=$app --key=pihole_version --value="$pihole_version"

ynh_app_setting_set --app=$app --key=overwrite_setupvars --value=1
ynh_app_setting_set --app=$app --key=overwrite_ftl --value=1
ynh_app_setting_set --app=$app --key=overwrite_nginx --value=1
ynh_app_setting_set --app=$app --key=overwrite_phpfpm --value=1
ynh_app_setting_set --app=$app --key=admin_mail_html --value=1

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================
ynh_script_progression --message="Finding an available port..." --weight=12

# Find a free port
port=$(ynh_find_port --port=4711)
if [ $port -gt 4720 ]
then
    ynh_die --message="The ports 4711 to 4720 are already in use. Pi-hole can't work on another port. Please try to free one of these ports."
fi
ynh_app_setting_set --app=$app --key=port --value=$port

# Disable the port 53 for upnp
ynh_exec_fully_quiet yunohost firewall disallow Both 53 --no-reload
ynh_exec_fully_quiet yunohost firewall allow Both 53 --no-upnp

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..." --weight=12

ynh_install_app_dependencies $app_depencencies

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression --message="Configuring system user..." --weight=2

# Create a dedicated system user
ynh_system_user_create --username=$app

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=4

ynh_app_setting_set --app=$app --key=final_path --value=$final_path
# Make a copy of local pihole repository (for Gravity)
pihole_local_repo="/etc/.pihole"
if [ "$pihole_version" == "Last 3.X" ]
then
    # Install the version 3.3.1
    ynh_setup_source --dest_dir="$pihole_local_repo" --source_id=app_3
    # Install admin dashboard
    ynh_setup_source --dest_dir="$final_path" --source_id=admin_dashboard_3
else
    # Install the last version available
    ynh_setup_source --dest_dir="$pihole_local_repo" --source_id=app_last
    # Install admin dashboard
    ynh_setup_source --dest_dir="$final_path" --source_id=admin_dashboard_last
fi

chown $app:www-data "$final_path"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring nginx web server..." --weight=2

# Create a dedicated nginx config
ynh_add_nginx_config

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring php-fpm..." --weight=2

# Create a dedicated php-fpm config
ynh_add_fpm_config --usage=low --footprint=low --dedicated_service

#=================================================
# SPECIFIC SETUP
#=================================================
# CREATE DIRECTORIES AND POPULATE THEM
#=================================================
ynh_script_progression --message="Creating and populating directories..."

pihole_storage="/etc/pihole"
mkdir -p "$pihole_storage"
chown $app: -R "$pihole_storage"

pihole_dir="/opt/pihole"
mkdir -p "$pihole_dir"

# Make a copy of Pi-Hole scripts
cp -a "$pihole_local_repo/gravity.sh" "$pihole_dir/"
cp -a $pihole_local_repo/advanced/Scripts/*.sh "$pihole_dir/"

# And copy this fucking COL_TABLE file...
cp -a "$pihole_local_repo/advanced/Scripts/COL_TABLE" "$pihole_dir/"

#=================================================
# COPY PI-HOLE MAIN SCRIPT
#=================================================
ynh_script_progression --message="Copying Pi-Hole main script..."

cp -a "$pihole_local_repo/pihole" /usr/local/bin/
cp -a "$pihole_local_repo/advanced/bash-completion/pihole" /etc/bash_completion.d/pihole

#=================================================
# CREATE LOG FILES
#=================================================

touch /var/log/{pihole,pihole-FTL}.log
chmod 644 /var/log/{pihole,pihole-FTL}.log
dnsmasq_user=$(grep DNSMASQ_USER= /etc/init.d/dnsmasq | cut -d'"' -f2)
chown $dnsmasq_user:root /var/log/{pihole,pihole-FTL}.log

#=================================================
# CREATE SUDOER FILE
#=================================================

# This sudoers config allow pihole to execute /usr/local/bin/pihole as root without password. Nothing more.
if [ "$pihole_version" == "Last 3.X" ]
then
    cp "$pihole_local_repo/advanced/pihole.sudo" /etc/sudoers.d/pihole
else
    cp "$pihole_local_repo/advanced/Templates/pihole.sudo" /etc/sudoers.d/pihole
fi
echo "$app ALL=NOPASSWD: /usr/local/bin/pihole" >> /etc/sudoers.d/pihole
# echo "Defaults secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin" >> /etc/sudoers.d/pihole
chmod 0440 /etc/sudoers.d/pihole

#=================================================
# INSTALL LOGROTATE SCRIPT FOR PI-HOLE
#=================================================

if [ "$pihole_version" == "Last 3.X" ]
then
    cp "$pihole_local_repo/advanced/logrotate" "$pihole_storage/logrotate"
else
    cp "$pihole_local_repo/advanced/Templates/logrotate" "$pihole_storage/logrotate"
fi
sed -i "/# su #/d;" "$pihole_storage/logrotate"

#=================================================
# INSTALLATION OF PIHOLE-FTL
#=================================================
ynh_script_progression --message="Installing PiHole-FTL..." --weight=30

# Get the source of Pi-Hole-FTL
FTL_temp_path=$(mktemp -d)
if [ "$pihole_version" == "Last 3.X" ]
then
    # Install the version 3.3.1
    ynh_setup_source --dest_dir="$FTL_temp_path" --source_id=FTL_3
else
    # Install the last version available
    ynh_setup_source --dest_dir="$FTL_temp_path" --source_id=FTL_last
fi

# Instead of downloading a binary file, we're going to compile it
( cd "$FTL_temp_path"
if [ "$pihole_version" == "Last available" ]
then
    ynh_exec_warn_less cmake .
fi
ynh_exec_warn_less make
ynh_exec_warn_less make install )
ynh_secure_remove --file="$FTL_temp_path"

cp "../conf/dns-servers.conf" "$pihole_storage"

ynh_add_config --template="../conf/pihole-FTL.conf" --destination="$pihole_storage/pihole-FTL.conf"

if [ "$pihole_version" == "Last 3.X" ]
then
    # Version 3.3.1
    cp -a $pihole_local_repo/advanced/pihole-FTL.service /etc/init.d/pihole-FTL
    chmod +x /etc/init.d/pihole-FTL
    ynh_exec_warn_less systemctl enable pihole-FTL --quiet
else
    # Last version available
    # Stopped dnsmasq to replace it by pihole-FTL
    ynh_systemd_action --action=stop --service_name=dnsmasq

    # Disable the real dnsmasq service
    ynh_exec_warn_less systemctl disable dnsmasq --quiet

    # And move the files that make the service available in systemd to really disable it
    mv /lib/systemd/system/dnsmasq.service /lib/systemd/system/.dnsmasq.service.backup_by_pihole
    mv /etc/init.d/dnsmasq /etc/init.d/.dnsmasq.backup_by_pihole

    # Move dnsmasq to preserve the current binary
    mv /usr/sbin/dnsmasq /usr/sbin/dnsmasq.backup_by_pihole
    # Replace dnsmasq by pihole-FTL
    # NOTE: pihole-FTL is actually a modified version of dnsmasq
    # https://github.com/pi-hole/FTL/tree/master/dnsmasq
    ln -s /usr/bin/pihole-FTL /usr/sbin/dnsmasq

    cp -a $pihole_local_repo/advanced/Templates/pihole-FTL.service /etc/init.d/pihole-FTL
    chmod +x /etc/init.d/pihole-FTL
    ynh_exec_warn_less systemctl enable pihole-FTL --quiet

    # Replace the service dnsmasq by pihole-FTL
    # That way, YunoHost can continue to use dnsmasq by actually using pihole-FTL
    ln -s /run/systemd/generator.late/pihole-FTL.service /etc/systemd/system/dnsmasq.service

    # Reload systemd config
    systemctl daemon-reload
fi

#=================================================
# BUILD VARIABLES FILE
#=================================================

setupVars="$pihole_storage/setupVars.conf"

# Get the default network interface
main_iface=$(ip route | grep --max-count=1 default | awk '{print $5;}')
echo "PIHOLE_INTERFACE=$main_iface" > $setupVars
echo "IPV4_ADDRESS=127.0.0.1" >> $setupVars
echo "IPV6_ADDRESS=::1" >> $setupVars
echo "PIHOLE_DNS_1=" >> $setupVars
echo "PIHOLE_DNS_2=" >> $setupVars
if [ $query_logging -eq 1 ]; then
    query_logging=true
else
    query_logging=false
fi
echo "QUERY_LOGGING=$query_logging" >> $setupVars
echo "INSTALL_WEB=true" >> $setupVars

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum --file="$setupVars"

#=================================================
# SET UP DNSMASQ CONFIG
#=================================================
ynh_script_progression --message="Setting up Dnsmasq config..." --weight=2

# ynh_systemd_action --action=stop --service_name=dnsmasq

pihole_dnsmasq_config="/etc/dnsmasq.d/01-pihole.conf"
cp "$pihole_local_repo/advanced/01-pihole.conf" $pihole_dnsmasq_config
# Use dns from /etc/resolv.dnsmasq.conf
ynh_replace_string --match_string="@DNS1@" --replace_string="" --target_file=$pihole_dnsmasq_config
ynh_replace_string --match_string="@DNS2@" --replace_string="" --target_file=$pihole_dnsmasq_config
ynh_replace_string --match_string="^no-resolv" --replace_string="#no-resolv" --target_file=$pihole_dnsmasq_config

ynh_replace_string --match_string="@INT@" --replace_string="$main_iface" --target_file=$pihole_dnsmasq_config
if [ "$query_logging" = "true" ]; then
    ynh_replace_string --match_string="^#log-queries" --replace_string="log-queries" --target_file=$pihole_dnsmasq_config
else
    ynh_replace_string --match_string="^log-queries" --replace_string="#log-queries" --target_file=$pihole_dnsmasq_config
fi

# Fix a too recent option for our dnsmasq version.
ynh_replace_string --match_string="log-queries=extra" --replace_string="log-queries" --target_file=$pihole_dnsmasq_config

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum --file="$pihole_dnsmasq_config"

# To prevent any conflict with the original dnsmasq config, comment cache-size in the original config.
ynh_replace_string --match_string="^cache-size=" --replace_string="#pihole# cache-size=" --target_file=/etc/dnsmasq.conf

#=================================================
# CONFIGURE DNS FOR THE LOCAL DOMAINS
#=================================================
ynh_script_progression --message="Configuring dns for the local domains..." --weight=7

# Find the IP associated to the network interface
localipv4=$(ip address | grep "${main_iface}\$" | awk '{print $2;}' | cut -d/ -f1)

# List all YunoHost domains
while read perdomain
do
    # Comment domain resolution in /etc/hosts on 127.0.0.1, because they can interfere with the local network resolution.
    ynh_replace_string --match_string="^127.0.0.1.*$perdomain" --replace_string="#Commented by pihole# &" --target_file=/etc/hosts

    # And add a resolution on the local IP instead
    grep -q "^$localipv4.*$perdomain" /etc/hosts || \
        echo "$localipv4	$perdomain #Added by pihole#" >> /etc/hosts
done <<< "$(yunohost domain list | grep "\." | sed 's/.*: \|.*- //')"

#=================================================
# ENABLE DHCP SERVER
#=================================================

if [ $enable_dhcp -eq 1 ]
then
    ynh_script_progression --message="Enabling dhcp server..."
    max_dhcp_range=250
    dhcp_range=100
    # Define the dhcp range from the current ip
    ip_beginning_part=$(echo "$localipv4" | cut -d. -f1-3)
    ip_fourth_part=$(echo "$localipv4" | cut -d. -f4)
    b_range=$(( $ip_fourth_part + $dhcp_range ))
    if [ $b_range -gt $max_dhcp_range ]; then
        b_range=$max_dhcp_range
    fi
    a_range=$(( $b_range - $dhcp_range ))

    # Get the gateway
    gateway=$(ip route | grep default | awk '{print $3;}')
    # And the mac adress
    hw_adress=$(ip link | grep -A1 "$main_iface" | tail -n1 | awk '{print $2;}')

    # Copy the config file
    cp "../conf/02-pihole-dhcp.conf" "/etc/dnsmasq.d/"

    # And set the config
    ynh_replace_string --match_string="__A_RANGE__" --replace_string="$ip_beginning_part.$a_range" --target_file="/etc/dnsmasq.d/02-pihole-dhcp.conf"
    ynh_replace_string --match_string="__B_RANGE__" --replace_string="$ip_beginning_part.$b_range" --target_file="/etc/dnsmasq.d/02-pihole-dhcp.conf"
    ynh_replace_string --match_string="__GATEWAY__" --replace_string="$gateway" --target_file="/etc/dnsmasq.d/02-pihole-dhcp.conf"

    # Set a static ip for the server.
    echo "dhcp-host=$hw_adress,$localipv4" > "/etc/dnsmasq.d/04-pihole-static-dhcp.conf"
fi

# Open the UDP port 67 for dhcp
ynh_exec_fully_quiet yunohost firewall allow UDP 67 --no-upnp

#=================================================
# SET VERSIONS FOR THE FOOTER OF THE WEB INTERFACE
#=================================================

echo "master master master" > $pihole_storage/localbranches
echo "$pihole_core_version $dashboard_version $FTL_version" | tee $pihole_storage/{GitHubVersions,localversions}  > /dev/null

#=================================================
# INSTALL CRON JOB
#=================================================

if [ "$pihole_version" == "Last 3.X" ]
then
    cp $pihole_local_repo/advanced/pihole.cron /etc/cron.d/pihole
else
    cp $pihole_local_repo/advanced/Templates/pihole.cron /etc/cron.d/pihole
fi

# Remove git usage for version. Which fails because we use here a release instead of master.
ynh_replace_string --match_string=".*updatechecker.*" --replace_string="#&" --target_file=/etc/cron.d/pihole

#=================================================
# RESTART DNSMASQ
#=================================================

# Restart dnsmasq only for the version 3.X, otherwise we're going to restart it twice.
if [ "$pihole_version" == "Last 3.X" ]
then
    ynh_script_progression --message="Restarting Dnsmasq..." --weight=2

    ynh_systemd_action --action=restart --service_name=dnsmasq
fi

#=================================================
# START PIHOLE-FTL
#=================================================

ynh_script_progression --message="Restarting PiHole-FTL..." --weight=2

ynh_systemd_action --action=restart --service_name=pihole-FTL

#=================================================
# BUILD THE LISTS WITH GRAVITY
#=================================================
ynh_script_progression --message="Building the lists with Gravity..." --weight=7

if [ "$pihole_version" == "Last 3.X" ]
then
    cp "$pihole_local_repo/adlists.default" "$pihole_storage/adlists.default"
else
    cp "../conf/adlists.default" "$pihole_storage/adlists.list"
fi
ynh_exec_warn_less /opt/pihole/gravity.sh

#=================================================
# SET UP CONF_REGEN HOOK
#=================================================

cp ../conf/dnsmasq_regenconf_hook /usr/share/yunohost/hooks/conf_regen/50-dnsmasq_$app
ynh_replace_string --match_string="__APP__" --replace_string="$app" --target_file="/usr/share/yunohost/hooks/conf_regen/50-dnsmasq_$app"

#=================================================
# GENERIC FINALISATION
#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

yunohost service add pihole-FTL --description="PiHole backend service" --log="/var/log/pihole-FTL.log"

#=================================================
# RESTRAIN THE ACCESS TO THE ADMIN ONLY
#=================================================
ynh_script_progression --message="Restraining the access to the admin only..." --weight=2

ynh_permission_update --permission="main" --add="$admin" --remove="all_users"

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading NGINX web server..." --weight=3

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# SEND A README FOR THE ADMIN
#=================================================

# Get main domain and buid the url of the admin panel of the app.
admin_panel="https://$(grep portal_domain /etc/ssowat/conf.json | cut -d'"' -f4)/yunohost/admin/#/apps/$app"

if [ $enable_dhcp -eq 1 ]
then
    dhcp_alert="You asked to use the internal DHCP server of dnsmasq with PiHole.
You should really read the __URL_TAG1__documentation about that__URL_TAG2__https://github.com/YunoHost-Apps/pihole_ynh/blob/master/dhcp.md__URL_TAG3__

"
else
    dhcp_alert=""
fi

echo "${dhcp_alert}You can configure this app easily by using the experimental __URL_TAG1__config-panel feature__URL_TAG2__$admin_panel/config-panel__URL_TAG3__.
You can also find some specific actions for this app by using the experimental __URL_TAG1__action feature__URL_TAG2__$admin_panel/actions__URL_TAG3__.

If you're facing an issue or want to improve this app, please open a new issue in this __URL_TAG1__project__URL_TAG2__https://github.com/YunoHost-Apps/pihole_ynh__URL_TAG3__." > mail_to_send

ynh_send_readme_to_admin --app_message="mail_to_send" --recipients="$admin" --type=install

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
