#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=2

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
port=$(ynh_app_setting_get --app=$app --key=port)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Check if the service is declared in YunoHost
if ynh_exec_fully_quiet yunohost service status pihole-FTL
then
	ynh_script_progression --message="Removing pihole-FTL service..." --weight=2
	yunohost service remove pihole-FTL
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Stopping and removing the systemd service..."

ynh_systemd_action --action=stop --service_name=pihole-FTL
ynh_exec_warn_less systemctl disable pihole-FTL --quiet
rm -f "/etc/init.d/pihole-FTL" "/usr/bin/pihole-FTL" "/var/run/pihole-FTL.pid" "/var/run/pihole-FTL.port"

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies..." --weight=7

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression --message="Removing app main directory..."

# Remove storage directory
ynh_secure_remove --file="/etc/pihole"
# Remove app directory
ynh_secure_remove --file="/opt/pihole"
# Remove admin panel directory
ynh_secure_remove --file="/var/www/pihole"
# Remove local clone of the repository
ynh_secure_remove --file="/etc/.pihole"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# REMOVE PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Removing PHP-FPM configuration..." --weight=2

# Remove the dedicated PHP-FPM config
ynh_remove_fpm_config

#=================================================
# CLOSE A PORT
#=================================================

if yunohost firewall list | grep -q "\- $port$"
then
	ynh_script_progression --message="Closing port $port..." --weight=6
	ynh_exec_warn_less yunohost firewall disallow TCP $port
fi

if yunohost firewall list | grep -q "\- 67$"
then
	ynh_script_progression --message="Closing port 67..." --weight=6
	ynh_exec_warn_less yunohost firewall disallow UDP 67
fi

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression --message="Removing various files..."

# Remove a cron file
ynh_secure_remove --file="/etc/cron.d/pihole"

# Remove logs
ynh_secure_remove --file="/var/log/pihole.log"
ynh_secure_remove --file="/var/log/pihole-FTL.log"

# Remove main script
ynh_secure_remove --file="/usr/local/bin/pihole"
ynh_secure_remove --file="/etc/bash_completion.d/pihole"

# Remove sudoer file
ynh_secure_remove --file="/etc/sudoers.d/pihole"

#=================================================
# REMOVE DNSMASQ CONFIG
#=================================================
ynh_script_progression --message="Removing Dnsmasq config..." --weight=2

ynh_systemd_action --action=stop --service_name=dnsmasq
ynh_secure_remove --file="/etc/dnsmasq.d/01-pihole.conf"
ynh_secure_remove --file="/etc/dnsmasq.d/02-pihole-dhcp.conf"
ynh_secure_remove --file="/etc/dnsmasq.d/03-pihole-wildcard.conf"
ynh_secure_remove --file="/etc/dnsmasq.d/04-pihole-static-dhcp.conf"

ynh_replace_string --match_string="#pihole# " --replace_string="" --target_file=/etc/dnsmasq.conf

#=================================================
# CLEAN /etc/hosts
#=================================================
ynh_script_progression --message="Clean /etc/hosts"

# Uncomment lines in /etc/hosts
ynh_replace_string --match_string="#Commented by pihole# " --replace_string="" --target_file=/etc/hosts

# And remove extra lines, added by PiHole
sed -i "/#Added by pihole#/d" /etc/hosts

#=================================================
# RESTART DNSMASQ
#=================================================
ynh_script_progression --message="Restarting Dnsmasq..."

ynh_systemd_action --action=restart --service_name=dnsmasq

#=================================================
# REMOVE CONF_REGEN HOOK
#=================================================

ynh_secure_remove --file=/usr/share/yunohost/hooks/conf_regen/50-dnsmasq_$app

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_script_progression --message="Removing the dedicated system user..." --weight=2

# Delete a system user
ynh_system_user_delete --username=$app

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
